Content:
    Fenix:
        root_dir: ${ROOT_DIR}/doc/content
    framework:
        root_dir: ${MOOSE_DIR}/framework/doc/content
    electromagnetics:
        root_dir: ${MOOSE_DIR}/modules/electromagnetics/doc/content
    ray_tracing:
        root_dir: ${MOOSE_DIR}/modules/ray_tracing/doc/content
    modules:
        root_dir: ${MOOSE_DIR}/modules/doc/content
        content:
            - help/finite_element_concepts/nodal_patch_recovery.md
            - application_usage/restart_recover.md

Renderer:
    type: MooseDocs.base.MaterializeRenderer
Extensions:
    MooseDocs.extensions.navigation:
        name: FENIX
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        remove:
            framework: !include ${MOOSE_DIR}/framework/doc/remove.yml
    MooseDocs.extensions.common:
        shortcuts: !include ${MOOSE_DIR}/framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms:
            framework: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
    MooseDocs.extensions.sqa:
        active: true
        categories:
            fenix: !include ${ROOT_DIR}/doc/sqa_fenix.yml
            framework: !include ${MOOSE_DIR}/framework/doc/sqa_framework.yml
            ray_tracing: !include ${MOOSE_DIR}/modules/ray_tracing/doc/sqa_ray_tracing.yml
            electromagnetics: !include ${MOOSE_DIR}/modules/electromagnetics/doc/sqa_electromagnetics.yml
        reports: !include ${ROOT_DIR}/doc/sqa_reports.yml
        repos:
            default: https://github.com/idaholab/fenix
    MooseDocs.extensions.template:
        active: true
